config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  namespace :admin do
    root "admins#login"
    resources :admins
    resources :categories
    resources :products
    resources :bills
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :product_bills
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_sizes
  has_many :product_bills
  scope :find_by_products, -> category_id {where category_id: category_id }
end

app/models/product_bill.rb
class ProductBill < ApplicationRecord
  belongs_to :product
  belongs_to :size
  belongs_to :bill
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :product_sizes 
    has_many :product_bills 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :bills
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :login_success, except: :destroy
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to admin_categories_path, :notice => ["Đăng nhập thành công!", "success"]
    else
      redirect_to admin_root_path, :notice => ["Đăng nhập sai!", "error"]
    end
  end
  def destroy
    log_out
    redirect_to admin_root_path, :notice => ["Đăng xuất thành công!", "success"]
  end

end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < Admin::ApplicationController
  def index
    @bills = Bill.all.page(params[:page]).per(10)     
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  # Check user has logged in before ?
  def logged_in?
    current_user.present?
  end

  def login_success
    if logged_in?
      redirect_to admin_categories_path, :notice => ["Ban đã đăng nhập", "success"]
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/login.html.erb
<DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.js"></script>
</head>
<body class="login">
  <div class="container">
    <div class="main-login main-center">
      <h1 align="center">INSAL</h1>
      <h4 align="center"> <%= t "admin.user_sign_in" %> </h4>
      <%= form_tag "/admin/admins", :method => "post", :class => "form-login" do %>
        <!-- EMAIL  -->
        <div class="form-group">
          <label for="name" class="cols-sm-2 control-label"> <%= t "admin.email" %> </label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span id="input-group" class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
              <%= text_field_tag :email, params[:email],  type:"text", class:"form-control", id:"email", placeholder: t("admin.enter_email") %>
            </div>
          </div>
        </div>
        <!-- PASSWORD  -->
        <div class="form-group">
          <label for="email" class="cols-sm-2 control-label"> <%= t "admin.password" %> </label>
          <div class="cols-sm-10">
            <div class="input-group">
              <span id="input-group" class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
              <%= password_field_tag :password, nil, type:"password", class:"form-control", id:"password", placeholder: t("admin.enter_password") %>
            </div>
          </div>
        </div>
        <div class="row" align="center">
          <a style="color: #ffffff; font-size: 15px;" href="/signup"> <%= t "admin.new_account" %> </a>
        </div>
        <div class="form-group">
          <%= submit_tag t("admin.sign_in"), type:"submit", id:"button", class:"btn btn-primary btn-lg btn-block login-button" %>
        </div>
        <script type="text/javascript">
          $(function(){
            var notice = "<%= !flash[:notice].nil? ? flash[:notice].first : '' %>"
            var type = "<%= !flash[:notice].nil? ? flash[:notice].last : '' %>"
            $.notify(notice, type );
          })
        </script>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
  </div>
  <strong>Copyright &copy; 2017-2018 <a href="#">INSAL Studio</a>.</strong> All rights
  reserved.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <a href="#" class="logo">
    <span class="logo-mini"><b>IN</b>S</span>
    <span class="logo-lg"><b>IN</b>SAL</span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="input-group input-group--custom">
      <div class="input-group-btn">
        <button type="button" class="btn btn-danger"><%= t "layouts.action" %></button>
      </div>
      <input type="text" class="form-control">
    </div>
    <div class="navbar-custom-menu locate-logout">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-cart-plus"></i>
          </a>
        </li>
        <li class="dropdown messages-menu">
          <%= link_to admin_admin_path(current_user), method: :delete, class:"dropdown-toggle" do %>
            <i class="fa fa-sign-out"></i>
            <span><%= t "layouts.log_out" %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_side-bar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="active">
        <%= link_to admin_categories_path do %>
          <i class="fa fa-dashboard"></i> <span><%= t "layouts.categories" %></span>
          <span class="pull-right-container">
          </span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_bills_path do %>
          <i class="fa fa-files-o"></i>
          <span><%= t "layouts.bills" %></span>
          <span class="pull-right-container">
            <span class="label label-primary pull-right">4</span>
          </span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_products_path do %>
           <i class="fa fa-circle-o text-red"></i>
          <span><%= t "layouts.products" %></span>
        <% end %>
      </li>
      <li class="header"><%= t "layouts.insights" %></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
    <%= render  "layouts/header" %>
    <%= render  "layouts/side-bar" %>
    <div class="content-wrapper">
      <section class="content">
        <%= yield %>
      </section>
    </div>
    <%= render  "layouts/footer" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      $(function(){
        var notice = "<%= !flash[:notice].nil? ? flash[:notice].first : '' %>"
        var type = "<%= !flash[:notice].nil? ? flash[:notice].last : '' %>"
        $.notify(notice, type );
      })
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<DOCTYPE html>
<html>
  <head>
    <title>InsalPhanxipang</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </div>
  </body>
</html>